version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"

  jobs:
    post_install:
      - pip install poetry
      - poetry config virtualenvs.create false
      - poetry install

sphinx:
  configuration: docs/conf.py

formats:
  - pdf
  - epub
